name: Flutter

on: 
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  flutter_jobs:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - name: setup flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      
      - name: install dependecies
        run: flutter pub get
